# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20180517_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date_of_sale', models.DateTimeField(default=django.utils.timezone.now)),
                ('starting_price', models.FloatField(blank=True)),
                ('min_bid', models.FloatField(blank=True)),
                ('immediate_price', models.FloatField(blank=True)),
                ('end_date_of_sale', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchased', models.BooleanField(default=False)),
                ('medium_rate', models.FloatField(blank=True)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Categories')),
                ('id_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatesProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('description', models.TextField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products')),
            ],
        ),
        migrations.CreateModel(
            name='RatesUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('description', models.TextField()),
                ('id_rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_rated_user', to=settings.AUTH_USER_MODEL)),
                ('id_rating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_rating_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bids',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Products'),
        ),
        migrations.AddField(
            model_name='bids',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
