# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180518_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='RatesProducts',
            new_name='RateProduct',
        ),
        migrations.RenameModel(
            old_name='RatesUsers',
            new_name='RateUser',
        ),
    ]
