# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medium_rate',
            field=models.FloatField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
