# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180518_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='medium_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
