# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180523_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='immediate_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='medium_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='starting_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
